name: gtk3-appindicator
version: 0.1
summary: Test appindicator using libappindicator
description: appindicator using libapindicator

grade: stable
confinement: strict

apps:
  gtk3-appindicator:
    command: desktop-launch $SNAP/simple-client
    plugs: [unity7]

parts:
  simple-client:
    plugin: make
    make-parameters:
      - ICON_PATH=/icons
    source: .
    build-packages:
      - pkg-config
    artifacts: ['simple-client', 'icons']
    after: [desktop-gtk3, indicator-support]

  desktop-gtk3:
    stage: [ -./**/libappindicator*.so.* ]

  indicator-support:
    plugin: autotools
    source: lp:~3v1n0/libappindicator/incons-paths-on-snap
    configflags:
      - --prefix=/usr
      - --with-gtk=3
      - --enable-gtk-doc=no
      - --enable-gtk-doc-html=no
      - --disable-tests
      - --disable-mono-test

    snap:
      - ./**/lib*.so.*
      - ./**/*.typelib

    build-packages:
      - at-spi2-core
      - gobject-introspection
      - intltool
      - libdbus-glib-1-dev
      - libdbusmenu-glib-dev
      - libdbusmenu-gtk3-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libindicator3-dev
      - python-all-dev
      - python-gtk2-dev
      - valac
