name: gtk3-appindicator
version: 0.1
summary: Test appindicator using libappindicator
description: appindicator using libapindicator

grade: stable
confinement: strict

apps:
  gtk3-appindicator:
    command: desktop-launch $SNAP/simple-client
    plugs: [unity7]

parts:
  simple-client:
    plugin: make
    make-parameters:
      - PREFIX=/snap/gtk3-appindicator/current
      - ICON_PATH=/icons
    source: .
    build-packages:
      - pkg-config
    artifacts: ['simple-client', 'icons']
    after: [desktop-gtk3, indicator-gtk3]

  desktop-gtk3:
    stage: [ -./**/libappindicator*.so.* ]
