name: qt4-systray
version: 4.8
summary: Qt4 systray example
description: Test indicator icons from a snap
grade: "devel"
confinement: strict

parts:
  indicator-support:
    plugin: cmake
    build-packages:
      - libdbusmenu-qt-dev
      - libqt4-dev
      - pkg-config
      - qt4-qmake
    source: lp:~3v1n0/sni-qt/icons-user-cache-on-snap

  qt4-systray:
    plugin: qmake
    qt-version: qt4
    source: .
    after:
      - desktop-qt4

apps:
  qt4-systray:
    command: desktop-launch $SNAP/usr/lib/qt4/examples/desktop/systray/systray
    plugs:
      - unity7
